import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {ReactQueryProvider} from '../app/components/ReactQueryProvider'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pokemon App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
        {children}
        <ReactQueryDevtools />
        </ReactQueryProvider>
        </body>
    </html>
  )
}
